### PR TITLE
Updating mbed-os to mbed-os-5.12.4

### PR DESCRIPTION
**Pull request by 0xc0170**
Please test this PR

If successful then merge, otherwise provide a known issue.
Once you get notification of the release being made public then tag Master with mbed-os-5.12.4 .

### CODE REVIEW

**Comment by 0xc0170** [comment]
@AnttiKauppila can you merge pls (not certain why CI is failing now) ?

**Comment by AnttiKauppila** [comment]
@kimlep01 Is investigating the CI failure.

**Comment by kimlep01** [comment]
Internal Jira ref: IOTCELL-2013

**Comment by 0xc0170** [comment]
Shall this be merged?

**Pull request merged**
