### PR TITLE
Add official example badge

### PR DESCRIPTION
**Pull request by gpsimenos**

### CODE REVIEW

**Comment by evedon** [comment]
@gpsimenos Target UBLOX_C030_U201 should be removed from Jenkinsfile as the target is no longer supported in Mbed 6

**Comment by gpsimenos** [comment]
> @gpsimenos Target UBLOX_C030_U201 should be removed from Jenkinsfile as the target is no longer supported in Mbed 6

Should I make the change in this PR or open a separate one?

**Comment by evedon** [comment]
> > @gpsimenos Target UBLOX_C030_U201 should be removed from Jenkinsfile as the target is no longer supported in Mbed 6
> 
> Should I make the change in this PR or open a separate one?

We will do the CI updates after the release.

**Comment by kimlep01** [comment]
Hi @evedon Jenkinsfile was updated in #189

**Comment by gpsimenos** [comment]
Rebased

**Pull request merged**
