### PR TITLE
TCP socket, and status info

### PR DESCRIPTION
**Pull request by TeemuKultala**

### CODE REVIEW

**Comment by adbridge** [comment]
@TeemuKultala So if I understand your change correctly it is going to sit there printing :
"Connection not ready..."
"Connection not ready..."
"Connection not ready..."

Every 4 seconds ? 
I will tag Marcelo to see if he thinks that is a good user experience.

I think he was expecting something more along the lines of :
"Establishing connection ..............................."  where each dot was added after a certain time.
@MarceloSalazar

**Comment by MarceloSalazar** [comment]
@adbridge is correct, I was thinking on something simple with simple dots.

**Comment by MarceloSalazar** [comment]
Thanks everyone!

**Comment by adbridge** [comment]
@TeemuKultala @hasnainvirk Can we get this merged please ?

**Pull request merged**
