### PR TITLE
Updating mbed-os to mbed-os-5.5.0

### PR DESCRIPTION
**Pull request by adbridge**
Please test/merge this PR and then tag Master with mbed-os-5.5.0

### CODE REVIEW

**Comment by adbridge** [comment]
@hasnainvirk Will you be owning this example ?

**Comment by hasnainvirk** [comment]
@adbridge I have moved to LoRaWAN team. Should I be owning it ? @SeppoTakalo What should be the SOP here ?

**Comment by hasnainvirk** [comment]
@adbridge Alright, got confirmation. Cellular team's tech lead @AnttiKauppila will own the repo.

**Comment by adbridge** [comment]
@hasnainvirk Thanks for confirmation. @AnttiKauppila  please be aware of mbed-os release schedules. Patch releases are every 2 weeks (Wed of odd week). Prior to that example owners are responsible for testing their example with latest mbed-os and merging. Will add you to owners list.

**Pull request closed without merging**
