### PR TITLE
Updating mbed-os to mbed-os-5.8.4

### PR DESCRIPTION
**Pull request by 0xc0170**
Please test this PR

If successful then merge, otherwise provide a known issue.
Once you get notification of the release being made public then tag Master with mbed-os-5.8.4 .

### CODE REVIEW

**Comment by AriParkkila** [comment]
We have a known problem with IAR and Ublox-C027 that prevents merge.

mbed compile -t IAR -m UBLOX_C027

mbed-os-example-cellular
Establishing connection ...Operator new[] out of memory

**Comment by 0xc0170** [comment]
Known issue since?

cc @adbridge

**Comment by AriParkkila** [comment]
The configuration was added in CI for 5.8.3 when it failed the first time.

It has been tested to not work also with previous versions, at least 5.8.2.

**Comment by adbridge** [comment]
> We have a known problem with IAR and Ublox-C027 that prevents merge.
> mbed compile -t IAR -m UBLOX_C027
Is this documented in the readme for this example? Looks like a running out of memory issue so not an actual problem with mbed-os itself...

**Comment by AriParkkila** [comment]
Out of memory issue with IAR is now reported as an issue #67.

**Comment by AriParkkila** [comment]
Handled by issue https://github.com/ARMmbed/mbed-os-example-cellular/issues/67

**Pull request closed without merging**
